AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Description: "A Cognito user pool for authenticating users"
    Properties:
      UserPoolName: "NgAppUserPool"
      UsernameAttributes: [email, phone_number]
      Schema:
        - Name: name
          AttributeDataType: String
          Required: false
        - Name: email
          AttributeDataType: String
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireSymbols: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Description: "App Client used by CognitoUserPool"
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ClientName: "ng-app-client"

